# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_db
spring.datasource.username=estoque_user
spring.datasource.password=senha_segura_123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ===== SQL Init (executa data.sql) =====
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# ===== Server =====
server.port=8080
server.servlet.context-path=/

# ===== Logging =====
logging.level.root=INFO
logging.level.com.estoque=DEBUG